<?php

// app/Notifications/CustomResetPasswordNotification.php
//
// WHY THIS EXISTS:
//   Laravel's default ResetPassword notification generates a URL pointing to
//   the /reset-password WEB route (a Blade page). We are a React SPA — there
//   is no Blade reset page. This custom notification overrides the URL to point
//   to the React frontend: http://localhost:5173/reset-password?token=...&email=...
//
// SAP EQUIVALENT: SU53 / self-service credential recovery
//
// MAILTRAP: All outgoing mail in local env is caught by Mailtrap automatically
//           because MAIL_MAILER=smtp points to sandbox.smtp.mailtrap.io in .env

namespace App\Notifications;

use Illuminate\Bus\Queueable;
use Illuminate\Notifications\Messages\MailMessage;
use Illuminate\Notifications\Notification;

class CustomResetPasswordNotification extends Notification
{
    use Queueable;

    /**
     * The raw password reset token generated by Laravel's Password Broker.
     * This is NOT the hashed token stored in password_reset_tokens table —
     * it is the plain token that must be passed back when resetting.
     */
    public function __construct(private readonly string $token) {}

    /**
     * This notification only uses the mail channel.
     * We do NOT queue it — for a beginner team, synchronous mail is safer
     * and easier to debug. If Mailtrap doesn't receive it, you will see the
     * error immediately in Laravel's logs.
     */
    public function via(object $notifiable): array
    {
        return ['mail'];
    }

    public function toMail(object $notifiable): MailMessage
    {
        // FRONTEND_URL must be set in .env — already confirmed: http://localhost:5173
        // We append token and email as query parameters so the React page can
        // read them with useSearchParams() and pre-fill the form.
        $frontendUrl = rtrim(config('app.frontend_url', 'http://localhost:5173'), '/');

        $resetUrl = $frontendUrl . '/reset-password?' . http_build_query([
            'token' => $this->token,
            'email' => $notifiable->getEmailForPasswordReset(),
        ]);

        return (new MailMessage)
            ->subject('Reset Your VFRB Enterprise Password')
            ->greeting('Hello, ' . $notifiable->name . '!')
            ->line('We received a request to reset the password for your VFRB Enterprise account.')
            ->line('Click the button below to choose a new password:')
            ->action('Reset My Password', $resetUrl)
            ->line('This link will **expire in 60 minutes**.')
            ->line('If you did not request a password reset, you can safely ignore this email.')
            ->line('Your account remains secure.')
            ->salutation('— VFRB Enterprise System');
    }
}
